public class TSTDF_WSC_API_SFECG extends TSTDF_Base {

    /*public override void queryAdditionalResults() {
        data.wsLogs = GW_sObject.queryRecords('WS_Log__c', ' Id <> null ORDER BY Id');
        data.wsScheduledCallouts = GW_sObject.queryRecords('WS_ScheduledCallout__c', ' Id <> null ORDER BY Id');
    }
    
    public override void createCustomSettings() {
  		List<Webservice_Settings__c> wss = new List<Webservice_Settings__c>();
        wss.add(new Webservice_Settings__c(Name = COUNTRYROLENAME +'_WSC_API_SFECG_v1_UAT', UseProxy__c=true, EndpointProxy__c='xxxxxx', Endpoint__c='yyyyyy', User__c='test_user'));
        wss.add(new Webservice_Settings__c(Name = COUNTRYROLENAME +'_WSC_API_SFECG_v1_PROD', UseProxy__c=true, EndpointProxy__c='xxxxxx', Endpoint__c='yyyyyy', User__c='test_user'));
    	wss.add(new Webservice_Settings__c(Name = 'WSC_Fiqas2_UAT', UseProxy__c=true, EndpointProxy__c='xxxxxx', Endpoint__c='yyyyyy', User__c='test_user'));
       	wss.add(new Webservice_Settings__c(Name = 'WSC_Fiqas2_PROD', UseProxy__c=true, EndpointProxy__c='xxxxxx', Endpoint__c='yyyyyy', User__c='test_user'));
        insert wss;
    }*/
}